services:
  nhds.jobs.semaphore.resource.factory-job:
    class: NHDS\Jobs\Semaphore\Resource\Factory
    shared: false
    calls:
      - [setName, ['job']]
      - [setSemaphoreResource, ['@nhds.jobs.semaphore.resource-job']]
      - [setSemaphoreResourceOwner, ['@nhds.semaphore.resource.owner.job']]
      - [setMutex, ['@nhds.jobs.semaphore.mutex.flock']]
  nhds.jobs.semaphore.resource.factory-maintain:
    class: NHDS\Jobs\Semaphore\Resource\Factory
    shared: false
    calls:
      - [setName, ['maintain']]
      - [setSemaphoreResource, ['@nhds.jobs.semaphore.resource-maintain']]
      - [setMutex, ['@nhds.jobs.semaphore.mutex.flock']]
  nhds.jobs.semaphore.resource.factory-schedule:
    class: NHDS\Jobs\Semaphore\Resource\Factory
    shared: false
    calls:
      - [setName, ['schedule']]
      - [setSemaphoreResource, ['@nhds.jobs.semaphore.resource-schedule']]
      - [setMutex, ['@nhds.jobs.semaphore.mutex.flock']]
  nhds.jobs.semaphore.resource.factory-server:
    class: NHDS\Jobs\Semaphore\Resource\Factory
    shared: false
    calls:
      - [setName, ['server']]
      - [setSemaphoreResource, ['@nhds.jobs.semaphore.resource-server']]
      - [setMutex, ['@nhds.jobs.semaphore.mutex.flock']]