parameters:
  process_pool_strategy.max_child_processes: 10
  process_pool_strategy.child_process_wait_throttle: 1
  process_pool_strategy.max_alarm_time: 0
  process_pool_strategy-server.max_child_processes: 1
  process_pool_strategy-server.child_process_wait_throttle: 1
  process_pool_strategy-server.max_alarm_time: 0
  process_pool_strategy-job.max_child_processes: 1
  process_pool_strategy-job.child_process_wait_throttle: 0
  process_pool_strategy-job.max_alarm_time: 0
  process_pool_strategy-empty.max_child_processes: 0
  process_pool_strategy-empty.child_process_wait_throttle: 0
  process_pool_strategy-empty.max_alarm_time: 0
services:
  nhds.jobs.process.pool.factory:
    class: NHDS\Jobs\Process\Pool\Factory
    shared: false
    calls:
      - [setMaxChildProcesses, ['%process_pool_strategy.max_child_processes%']]
      - [setChildProcessWaitThrottle, ['%process_pool_strategy.child_process_wait_throttle%']]
      - [setMaxAlarmTime, ['%process_pool_strategy.max_alarm_time%']]
      - [setProcessPool, ['@process.pool']]
      - [setProcessPoolStrategy, ['@process.pool.strategy']]
      - [setProcessCollection, ['@process.collection']]
  process.pool.factory:
    alias: nhds.jobs.process.pool.factory
  nhds.jobs.process.pool.factory-server:
    class: NHDS\Jobs\Process\Pool\Factory
    shared: false
    calls:
      - [setMaxChildProcesses, ['%process_pool_strategy-server.max_child_processes%']]
      - [setChildProcessWaitThrottle, ['%process_pool_strategy-server.child_process_wait_throttle%']]
      - [setMaxAlarmTime, ['%process_pool_strategy-server.max_alarm_time%']]
      - [setProcessPool, ['@process.pool']]
      - [setProcessPoolStrategy, ['@process.pool.strategy-server']]
      - [setProcessCollection, ['@process.collection-server']]
  process.pool.factory-server:
    alias: nhds.jobs.process.pool.factory-server
  nhds.jobs.process.pool.factory-job:
    class: NHDS\Jobs\Process\Pool\Factory
    shared: false
    calls:
      - [setMaxChildProcesses, ['%process_pool_strategy-job.max_child_processes%']]
      - [setChildProcessWaitThrottle, ['%process_pool_strategy-job.child_process_wait_throttle%']]
      - [setMaxAlarmTime, ['%process_pool_strategy-job.max_alarm_time%']]
      - [setProcessPool, ['@process.pool']]
      - [setProcessPoolStrategy, ['@process.pool.strategy-job']]
      - [setProcessCollection, ['@process.collection-job']]
  process.pool.factory-job:
    alias: nhds.jobs.process.pool.factory-job
  nhds.jobs.process.pool.factory-empty:
    class: NHDS\Jobs\Process\Pool\Factory
    shared: false
    calls:
      - [setMaxChildProcesses, ['%process_pool_strategy-empty.max_child_processes%']]
      - [setChildProcessWaitThrottle, ['%process_pool_strategy-empty.child_process_wait_throttle%']]
      - [setMaxAlarmTime, ['%process_pool_strategy-empty.max_alarm_time%']]
      - [setProcessPool, ['@process.pool']]
      - [setProcessPoolStrategy, ['@process.pool.strategy-job']]
      - [setProcessCollection, ['@process.collection-empty']]
  process.pool.factory-empty:
    alias: nhds.jobs.process.pool.factory-empty