parameters:
  process_pool_strategy.max_child_processes: 30
  process_pool_strategy.child_process_wait_throttle: 1
  process_pool_strategy.max_alarm_time: 30
  process_pool_strategy-server.max_child_processes: 1
  process_pool_strategy-server.child_process_wait_throttle: 1
  process_pool_strategy-server.max_alarm_time: 3600
services:
  nhds.jobs.process.pool.factory:
    class: NHDS\Jobs\Process\Pool\Factory
    sahred: false
    calls:
      - [setMaxChildProcesses, ['%process_pool_strategy.max_child_processes%']]
      - [setChildProcessWaitThrottle, ['%process_pool_strategy.child_process_wait_throttle%']]
      - [setMaxAlarmTime, ['%process_pool_strategy.max_alarm_time%']]
      - [setProcessPool, ['@process.pool']]
      - [setProcessPoolStrategy, ['@process.pool.strategy']]
      - [setProcessCollection, ['@nhds.jobs.process.collection']]
  nhds.jobs.process.pool.factory-server:
    class: NHDS\Jobs\Process\Pool\Factory
    shared: false
    calls:
      - [setMaxChildProcesses, ['%process_pool_strategy-server.max_child_processes%']]
      - [setChildProcessWaitThrottle, ['%process_pool_strategy-server.child_process_wait_throttle%']]
      - [setMaxAlarmTime, ['%process_pool_strategy-server.max_alarm_time%']]
      - [setProcessPool, ['@process.pool']]
      - [setProcessPoolStrategy, ['@process.pool.strategy-server']]
      - [setProcessCollection, ['@nhds.jobs.process.collection-server']]
  process.pool.factory:
    alias: nhds.jobs.process.pool.factory
  process.pool.factory-server:
    alias: nhds.jobs.process.pool.factory-server