parameters:
  process.pool.logger.process_id_padding: 6
  process.pool.logger.path_padding: 63
services:
  nhds.jobs.process.pool.logger:
    class: NHDS\Jobs\Process\Pool\Logger
    calls:
      - [setIsEnabled, [true]]
      - [setTime, ['@nhds.toolkit.time']]
      - [setProcessIdPadding, ['%process.pool.logger.process_id_padding%']]
      - [setProcessPathPadding, ['%process.pool.logger.path_padding%']]
  process.pool.logger:
    alias: nhds.jobs.process.pool.logger