services:
  nhds.jobs.process.pool.logger:
    class: NHDS\Jobs\Process\Pool\Logger
    calls:
      - [setIsEnabled, [true]]
      - [setTime, ['@nhds.toolkit.time']]
  process.pool.logger:
    alias: nhds.jobs.process.pool.logger