parameters:
  process.pool.logger.process_id_padding: 6
  process.pool.logger.path_padding: 80
  process.pool.logger.is_enabled: true
services:
  nhds.jobs.process.pool.logger:
    class: NHDS\Jobs\Process\Pool\Logger
    calls:
      - [setIsEnabled, ['%process.pool.logger.is_enabled%']]
      - [setTime, ['@nhds.toolkit.time']]
      - [setProcessIdPadding, ['%process.pool.logger.process_id_padding%']]
      - [setProcessPathPadding, ['%process.pool.logger.path_padding%']]
  process.pool.logger:
    alias: nhds.jobs.process.pool.logger