services:
  nhds.jobs.process.pool.server:
    class: NHDS\Jobs\Process\Pool\Server
    calls:
      - [setLogger, ['@process.pool.logger']]
      - [setSemaphore, ['@nhds.jobs.semaphore']]
      - [addSemaphoreResourceFactory, ['@nhds.jobs.semaphore.resource.factory-server']]
      - [setProcessPoolFactory, ['@process.pool.factory-server']]