services:
  nhds.jobs.process.pool.server:
    public: true
    class: NHDS\Jobs\Process\Pool\Server
    calls:
      - [setLogger, ['@process.pool.logger']]
      - [setSemaphore, ['@semaphore']]
      - [addSemaphoreResourceFactory, ['@semaphore.resource.factory-server']]
      - [setProcessPoolFactory, ['@process.pool.factory-server']]
      - [setTypeCode, ['server']]
      - [setTerminationSignalNumber, ['@=constant("SIGTERM")']]
      - [setUuidMaximumInteger, [9999999999]]
      - [setProcessRegistry, ['@process.registry']]
      - [setProcessSignal, ['@process.signal']]
      - [setTitlePrefix, ['%process.title.prefix%']]
  process.pool.server:
    public: true
    alias: nhds.jobs.process.pool.server