services:
  nhds.jobs.process.pool.server:
    class: NHDS\Jobs\Process\Pool\Server
    calls:
      - [setLogger, ['@nhds.jobs.process.pool.logger']]
      - [setTime, ['@nhds.toolkit.time']]
      - [setPool, ['@nhds.jobs.process.pool']]
      - [addSemaphoreResourceFactory, ['@nhds.jobs.semaphore.resource.factory-server']]
      - [setSemaphore, ['@nhds.jobs.semaphore']]