services:
  nhds.jobs.process.pool.strategy:
    class: NHDS\Jobs\Process\Pool\Strategy
    calls:
      - [setMaxProcesses, ['%process_pool_strategy.max_processes%']]
      - [setProcessWaitThrottle, ['%process_pool_strategy.process_wait_throttle%']]
      - [setMaxAlarmTime, ['%process_pool_strategy.max_alarm_time%']]
      - [setLogger, ['@nhds.jobs.process.pool.logger']]
      - [setPool, ['@nhds.jobs.process.pool']]
      - [setProcessCollection, ['@nhds.jbs.process.collection']]
  strategy:
    alias: nhds.jobs.process.pool.strategy