parameters:
  process.pool.strategy.maximum_load_average: 10.0
  process.pool.strategy-server.maximum_load_average: 10.0
services:
  nhds.jobs.process.pool.strategy:
    shared: false
    class: NHDS\Jobs\Process\Pool\Strategy
    calls:
      - [setAlarmProcessTypeCode, ['job']]
      - [setLogger, ['@process.pool.logger']]
      - [setMaximumLoadAverage, ['%process.pool.strategy.maximum_load_average%']]
  process.pool.strategy:
    alias: nhds.jobs.process.pool.strategy
  nhds.jobs.process.pool.strategy-server:
    shared: false
    class: NHDS\Jobs\Process\Pool\Strategy
    calls:
      - [setAlarmProcessTypeCode, ['root']]
      - [setFillProcessTypeCode, ['root']]
      - [setLogger, ['@process.pool.logger']]
      - [setMaximumLoadAverage, ['%process.pool.strategy.maximum_load_average%']]
  process.pool.strategy-server:
    alias: nhds.jobs.process.pool.strategy-server