services:
  nhds.jobs.process.pool.strategy:
    shared: false
    class: NHDS\Jobs\Process\Pool\Strategy
    calls:
      - [setAlarmProcessTypeCode, ['job']]
      - [setLogger, ['@process.pool.logger']]
  nhds.jobs.process.pool.strategy-server:
    shared: false
    class: NHDS\Jobs\Process\Pool\Strategy
    calls:
      - [setAlarmProcessTypeCode, ['root']]
      - [setFillProcessTypeCode, ['root']]
      - [setLogger, ['@process.pool.logger']]
  process.pool.strategy:
    alias: nhds.jobs.process.pool.strategy
  process.pool.strategy-server:
    alias: nhds.jobs.process.pool.strategy-server