services:
  nhds.jobs.process.job.required:
    shared: false
    class: NHDS\Jobs\Process\Job\Required
    calls:
      - [setLogger, ['@process.pool.logger']]
      - [setForeman, ['@foreman']]
      - [setMaintainer, ['@maintainer']]
      - [setScheduler, ['@scheduler']]
      - [setBootstrap, ['@worker.bootstrap']]
      - [setTypeCode, ['job.required']]
      - [setProcessStrategy, ['@process.strategy.process_control']]
      - [setSelector, ['@selector']]
      - [setTerminationSignalNumber, ['@=constant("SIGTERM")']]
      - [setUuidMaximumInteger, [9999999999]]
      - [setProcessRegistry, ['@process.registry']]
      - [setProcessPoolFactory, ['@process.pool.factory-job']]
  process.job.required:
    alias: nhds.jobs.process.job.required