services:
  Neighborhoods\Kojo\Api\V1\Worker\ServiceInterface:
    class: Neighborhoods\Kojo\Api\V1\Worker\Service
    shared: false
    calls:
      - [setServiceUpdateCompleteFailedFactory, ['@Neighborhoods\Kojo\Service\Update\Complete\Failed\FactoryInterface']]
      - [setServiceUpdateCompleteSuccessFactory, ['@Neighborhoods\Kojo\Service\Update\Complete\Success\FactoryInterface']]
      - [setServiceUpdateHoldFactory, ['@Neighborhoods\Kojo\Service\Update\Hold\FactoryInterface']]
      - [setServiceUpdateRetryFactory, ['@Neighborhoods\Kojo\Service\Update\Retry\FactoryInterface']]
      - [setApiV1JobSchedulerFactory, ['@Neighborhoods\Kojo\Api\V1\Job\Scheduler\FactoryInterface']]
      - [setApiV1Logger, ['@Neighborhoods\Kojo\Api\V1\LoggerInterface']]