services:
  nhds.jobs.console.command.db.teardown.uninstall:
    class: NHDS\Jobs\Console\Command\Db\TearDown\Uninstall
    calls:
      - [setBootstrap, ['@bootstrap']]
      - [setDbTearDown, ['@nhds.jobs.db.teardown']]