services:
  nhds.jobs.console.command.db.teardown.uninstall:
    class: NHDS\Jobs\Console\Command\Db\TearDown\Uninstall
    calls:
      - [setBootstrap, ['@worker.bootstrap']]
      - [setDbTearDown, ['@db.teardown']]
  console.command.db.teardown.uninstall:
    alias: nhds.jobs.console.command.db.teardown.uninstall