services:
  neighborhoods.kojo.db.connection.container-job:
    class: Neighborhoods\Kojo\Db\Connection\Container
    calls:
      - [setName, [!php/const \Neighborhoods\Kojo\Db\Connection\ContainerInterface::NAME_JOB]]
  db.connection.container-job:
    alias: neighborhoods.kojo.db.connection.container-job
  neighborhoods.kojo.db.connection.container-schema:
    class: Neighborhoods\Kojo\Db\Connection\Container
    calls:
      - [setName, [!php/const \Neighborhoods\Kojo\Db\Connection\ContainerInterface::NAME_SCHEMA]]
  db.connection.container-schema:
    alias: neighborhoods.kojo.db.connection.container-schema