services:
  nhds.jobs.state.service:
    class: NHDS\Jobs\State\Service
    shared: false
    calls:
      - [setTime, ['@nhds.toolkit.time']]
      - [setTypeRepository, ['@type.repository']]
  state.service:
    alias: nhds.jobs.state.service