services:
  nhds.jobs.db.connection.container-schema:
    class: NHDS\Jobs\Db\Connection\Container
    calls:
      - [setName, ["@=constant('NHDS\\\\Jobs\\\\Db\\\\Connection\\\\ContainerInterface::NAME_SCHEMA')"]]
#      - [setPdo, ["@pdo"]]
  nhds.jobs.db.connection.container-job:
    class: NHDS\Jobs\Db\Connection\Container
    calls:
      - [setName, ["@=constant('NHDS\\\\Jobs\\\\Db\\\\Connection\\\\ContainerInterface::NAME_JOB')"]]
  bootstrap_example:
    class: NHDS\Jobs\Example\Process\Pool\Type\Job\BootstrapExample
    calls:
      - [addDbConnectionContainer, ['@nhds.jobs.db.connection.container-job']]
#      - [setPdo, ["@pdo"]]
#  pdo:
#    class: \Pdo
#    arguments: ['mysql:dbname=jobs;host=mysql', 'root', 'nhdsroot']