services:
  nhds.jobs.db.connection.container-schema:
    class: NHDS\Jobs\Db\Connection\Container
    calls:
      - [setName, ["@=constant('NHDS\\\\Jobs\\\\Db\\\\Connection\\\\ContainerInterface::NAME_SCHEMA')"]]
  nhds.jobs.db.connection.container-job:
    class: NHDS\Jobs\Db\Connection\Container
    calls:
      - [setName, ["@=constant('NHDS\\\\Jobs\\\\Db\\\\Connection\\\\ContainerInterface::NAME_JOB')"]]
  nhds.jobs.example.worker.bootstrap:
    class: NHDS\Jobs\Example\Worker\Bootstrap
    calls:
      - [addDbConnectionContainer, ['@nhds.jobs.db.connection.container-job']]
      - [addDbConnectionContainer, ['@nhds.jobs.db.connection.container-schema']]
  bootstrap:
    alias: nhds.jobs.example.worker.bootstrap