services:
  neighborhoods.kojo.db.connection.container-schema:
    class: Neighborhoods\Kojo\Db\Connection\Container
    calls:
      - [setName, [!php/const \Neighborhoods\Kojo\Db\Connection\ContainerInterface::NAME_SCHEMA]]
  neighborhoods.kojo.db.connection.container-job:
    class: Neighborhoods\Kojo\Db\Connection\Container
    calls:
      - [setName, [!php/const \Neighborhoods\Kojo\Db\Connection\ContainerInterface::NAME_JOB]]
  neighborhoods.kojo.example.worker.bootstrap:
    class: Neighborhoods\Kojo\Example\Worker\Bootstrap
    calls:
      - [addDbConnectionContainer, ['@neighborhoods.kojo.db.connection.container-job']]
      - [addDbConnectionContainer, ['@neighborhoods.kojo.db.connection.container-schema']]
  worker.bootstrap:
    alias: neighborhoods.kojo.example.worker.bootstrap