services:
  nhds.jobs.message.broker.redis:
    class: NHDS\Jobs\Message\Broker\Redis
    shared: false
    calls:
      - [setLogger, ['@process.pool.logger']]
      - [setSubscriptionChannelName, ['job_listener_subscribe']]
      - [setPublishChannelName, ['job_listener_publish']]
      - [setRedisRepository, ['@redis.repository']]
  message.broker.redis:
    alias: nhds.jobs.message.broker.redis
  nhds.jobs.message.broker.redis[process.listener.mutex.redis]:
    class: NHDS\Jobs\Message\Broker\Redis
    shared: false
    calls:
      - [setLogger, ['@process.pool.logger']]
      - [setRedisRepository, ['@redis.repository']]
  message.broker.redis[process.listener.mutex.redis]:
    alias: nhds.jobs.message.broker.redis[process.listener.mutex.redis]