services:
  nhds.jobs.message.broker.redis:
    class: NHDS\Jobs\Message\Broker\Redis
    shared: false
    calls:
      - [setLogger, ['@nhds.jobs.process.pool.logger']]
      - [setPort, ['6379']]
      - [setHost, ['redis']]
      - [setSubscriptionChannelName, ['job_listener_subscribe']]
      - [setPublishChannelName, ['job_listener_publish']]