services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: true
  nhds.toolkit.time:
    public: true
    class: NHDS\Toolkit\Time
  nhds.watch.fixture.expression.numberpool:
    class: Neighborhoods\Scaffolding\Fixture\Expression\NumberPool
imports:
   - { resource: TestCase/Service.yml }