services:
  nhds.jobs.semaphore.resource-job:
    class: NHDS\Jobs\Semaphore\Resource
    shared: false
    calls:
      - [setIsBlocking, [false]]
  nhds.jobs.semaphore.resource-maintainer_delete:
    class: NHDS\Jobs\Semaphore\Resource
    shared: false
    calls:
      - [setResourceName, ['maintainer_delete.lock']]
      - [setResourcePath, ['nhds/jobs']]
      - [setIsBlocking, [false]]
  nhds.jobs.semaphore.resource-update_pending_jobs:
    class: NHDS\Jobs\Semaphore\Resource
    shared: false
    calls:
      - [setResourceName, ['update_pending_jobs.lock']]
      - [setResourcePath, ['nhds/jobs']]
      - [setIsBlocking, [false]]
  nhds.jobs.semaphore.resource-reschedule_jobs:
    class: NHDS\Jobs\Semaphore\Resource
    shared: false
    calls:
      - [setResourceName, ['reschedule_jobs.lock']]
      - [setResourcePath, ['nhds/jobs']]
      - [setIsBlocking, [false]]
  nhds.jobs.semaphore.resource-schedule:
    class: NHDS\Jobs\Semaphore\Resource
    calls:
      - [setResourceName, ['schedule.lock']]
      - [setResourcePath, ['nhds/jobs']]
      - [setIsBlocking, [false]]
    shared: false
  nhds.jobs.semaphore.resource-server:
    class: NHDS\Jobs\Semaphore\Resource
    shared: false
    calls:
      - [setResourceName, ['server.lock']]
      - [setResourcePath, ['nhds/jobs']]
      - [setIsBlocking, [false]]