services:
  nhds.jobs.semaphore.resource-job:
    class: NHDS\Jobs\Semaphore\Resource
    shared: false
      - [setIsBlocking, [false]]
  nhds.jobs.semaphore.resource-maintain:
    class: NHDS\Jobs\Semaphore\Resource
    shared: false
    calls:
      - [setResourceName, ['maintain.lock']]
      - [setResourcePath, ['nhds/jobs']]
      - [setIsBlocking, [false]]
  nhds.jobs.semaphore.resource-schedule:
    class: NHDS\Jobs\Semaphore\Resource
    calls:
      - [setResourceName, ['schedule.lock']]
      - [setResourcePath, ['nhds/jobs']]
      - [setIsBlocking, [false]]
    shared: false
  nhds.jobs.semaphore.resource-server:
    class: NHDS\Jobs\Semaphore\Resource
    shared: false
    calls:
      - [setResourceName, ['server.lock']]
      - [setResourcePath, ['nhds/jobs']]
      - [setIsBlocking, [false]]