services:
  nhds.jobs.cache_item_pool.factory:
    class: NHDS\Jobs\CacheItemPool\Factory
    public: false
    shared: true
    calls:
      - [setRedisRepository, ['@redis.repository']]
  cache_item_pool.factory:
    alias: nhds.jobs.cache_item_pool.factory
    public: false