services:
  nhds.jobs.cache_item_pool.repository:
    class: NHDS\Jobs\CacheItemPool\Repository
    shared: true
    public: false
    calls:
      - [setCacheItemPoolFactory, ['@cache_item_pool.factory']]
      - [setProcessRegistry, ['@process.registry']]
  cache_item_pool.repository:
    alias: nhds.jobs.cache_item_pool.repository
    public: false