services:
  nhds.jobs.process.type.job:
    class: NHDS\Jobs\Process\Type\Job
    calls:
      - [setPool, ['@nhds.jobs.process.pool']]
      - [setLogger, ['@nhds.jobs.process.pool.logger']]
      - [setBrokerTypeCollection, ['@nhds.jobs.message.broker.type.collection-job']]
      - [setBrokerTypeCode, ['job_broker']]
      - [setForeman, ['@nhds.jobs.foreman']]
      - [setMaintainer, ['@nhds.jobs.maintainer']]
      - [setScheduler, ['@nhds.jobs.scheduler']]
      - [setBootstrap, ['@bootstrap']]
      - [setTypeCode, ['job']]