services:
  nhds.jobs.db.tear_down:
    public: true
    class: NHDS\Jobs\Db\TearDown
    calls:
      - [addVersion, ["@db.tear_down.schema.version_6_0_0"]]
      - [addVersion, ["@db.tear_down.schema.version.5_0_0"]]
      - [addVersion, ["@db.tear_down.schema.version.4_0_0"]]
      - [addVersion, ["@db.tear_down.schema.version.3_0_0"]]
      - [addVersion, ["@db.tear_down.schema.version.2_0_0"]]
      - [addVersion, ["@db.tear_down.schema.version.1_0_0"]]
      - [addVersion, ["@db.tear_down.schema.version.0_0_0"]]
  db.tear_down:
    public: true
    alias: nhds.jobs.db.tear_down