services:
  neighborhoods.kojo.service.update.complete.failed:
    class: Neighborhoods\Kojo\Service\Update\Complete\Failed
    shared: false
  service.update.complete.failed:
    alias: neighborhoods.kojo.service.update.complete.failed