services:
  nhds.jobs.redis.factory:
    class: NHDS\Jobs\Redis\Factory
    public: false
    shared: true
    calls:
      - [addOption, [!php/const \Redis::OPT_READ_TIMEOUT, '-1']]
      - [setHost, ['%env(REDIS_HOST)%']]
      - [setPort, ['%env(REDIS_PORT)%']]
  redis.factory:
    alias: nhds.jobs.redis.factory
    public: false