services:
  nhds.jobs.redis.repository:
    class: NHDS\Jobs\Redis\Repository
    public: false
    shared: true
    calls:
      - [setProcessRegistry, ['@process.registry']]
      - [setRedisFactory, ['@redis.factory']]
  redis.repository:
    alias: nhds.jobs.redis.repository
    public: false