services:
  neighborhoods.kojo.db.setup.schema.version_6_0_0:
    class: Neighborhoods\Kojo\Db\Setup\Schema\Version_6_0_0
    calls:
      - [addDbConnectionContainer, ['@db.connection.container-schema']]
  db.setup.schema.version_6_0_0:
    alias: neighborhoods.kojo.db.setup.schema.version_6_0_0