services:
  neighborhoods.kojo.process.listener.mutex.redis:
    class: Neighborhoods\Kojo\Process\Listener\Mutex\Redis
    public: false
    shared: false
    calls:
      - [setTypeCode, ['listener.mutex.redis']]
      - [setLogger, ['@process.pool.logger']]
      - [setProcessStrategy, ['@process.strategy.process_control']]
      - [setProcessRegistry, ['@process.registry']]
      - [setTerminationSignalNumber, ['@=constant("SIGKILL")']]
      - [setUuidMaximumInteger, [9999999999]]
      - [setBrokerTypeCollection, ['@neighborhoods.kojo.message.broker.type.collection-job']]
      - [setBrokerTypeCode, ['process.listener.mutex.redis']]
      - [setProcessPoolFactory, ['@process.pool.factory-empty']]
      - [setRedisFactory, ['@redis.factory']]
      - [setProcessSignal, ['@process.signal']]
      - [setTitlePrefix, ['%process.title.prefix%']]
  process.listener.mutex.redis:
    alias: neighborhoods.kojo.process.listener.mutex.redis
    public: false