services:
  nhds.jobs.service.update.complete.success.factory:
    class: NHDS\Jobs\Service\Update\Complete\Success\Factory
    calls:
      - [setStateService, ['@state.service']]
      - [setServiceUpdateCompleteSuccess, ['@service.update.complete.success']]
  service.update.complete.success.factory:
    alias: nhds.jobs.service.update.complete.success.factory