services:
  nhds.jobs.db.connection.container-job:
    class: NHDS\Jobs\Db\Connection\Container
    calls:
      - [setName, ["@=constant('NHDS\\\\Jobs\\\\Db\\\\Connection\\\\ContainerInterface::NAME_JOB')"]]
  nhds.jobs.db.connection.container-schema:
    class: NHDS\Jobs\Db\Connection\Container
    calls:
      - [setName, ["@=constant('NHDS\\\\Jobs\\\\Db\\\\Connection\\\\ContainerInterface::NAME_SCHEMA')"]]