services:
  nhds.toolkit.time:
    class: NHDS\Toolkit\Time
  symfony.component.cache.adpater.redisadapter:
    class: Symfony\Component\Cache\Adapter\RedisAdapter
    arguments: ['@redis']
  symfony.component.expressionlanguage.expressionlanguage:
    class: \Symfony\Component\ExpressionLanguage\ExpressionLanguage
  redis:
    class: \Redis
    calls:
      - [connect, ['redis', '6379']]
  symfony.component.console.application:
    class: Symfony\Component\Console\Application
    calls:
      - [add, ['@nhds.jobs.console.command.process.pool.server.start']]
      - [add, ['@nhds.jobs.console.command.db.setup.install']]
      - [add, ['@nhds.jobs.console.command.db.teardown.uninstall']]