parameters:
  process_pool_strategy.max_processes: 30
  process_pool_strategy.process_wait_throttle: 1
  process_pool_strategy.max_alarm_time: 300
services:
  nhds.toolkit.time:
    class: NHDS\Toolkit\Time
  nhds.jobs.process.pool.logger:
    class: NHDS\Jobs\Process\Pool\Logger
    calls:
      - [setIsEnabled, [true]]
      - [setTime, ['@nhds.toolkit.time']]
      - [setPool, ['@nhds.jobs.process.pool']]
  nhds.jobs.message.broker.redis:
    class: NHDS\Jobs\Message\Broker\Redis
    calls:
      - [setLogger, ['@nhds.jobs.process.pool.logger']]
      - [setPort, ['6379']]
      - [setHost, ['redis']]
      - [setSubscriptionChannelName, ['job_queue']]
      - [setPublishChannelName, ['job_queue']]
    shared: false
  nhds.jobs.message.broker.type.collection-job:
    class: NHDS\Jobs\Message\Broker\Type\Collection
    calls:
      - [addBrokerType, ['job_broker', '@nhds.jobs.message.broker.redis']]
  nhds.jobs.db.connection.container-job:
    class: NHDS\Jobs\Db\Connection\Container
    calls:
      - [setName, ["@=constant('NHDS\\\\Jobs\\\\Db\\\\Connection\\\\ContainerInterface::NAME_JOB')"]]
  nhds.jobs.db.connection.container-schema:
    class: NHDS\Jobs\Db\Connection\Container
    calls:
      - [setName, ["@=constant('NHDS\\\\Jobs\\\\Db\\\\Connection\\\\ContainerInterface::NAME_SCHEMA')"]]
  nhds.jobs.semaphore:
    class: NHDS\Jobs\Semaphore
  nhds.jobs.semaphore.mutex.flock:
    class: NHDS\Jobs\Semaphore\Mutex\Flock
    calls:
      - [setFileMode, ['c']]
      - [setDirectoryMode, ['0777']]
    shared: false
  symfony.component.cache.adpater.redisadapter:
    class: Symfony\Component\Cache\Adapter\RedisAdapter
    arguments: ['@redis']
  redis:
    class: \Redis
    calls:
      - [connect, ['redis', '6379']]