services:
  nhds.toolkit.time:
    class: NHDS\Toolkit\Time
  symfony.component.expressionlanguage.expressionlanguage:
    class: \Symfony\Component\ExpressionLanguage\ExpressionLanguage
  nhds.jobs.symfony.component.console.application:
    public: true
    class: Symfony\Component\Console\Application
    calls:
      - [add, ['@console.command.process.pool.server.start']]
      - [add, ['@console.command.db.setup.install']]
      - [add, ['@console.command.db.tear_down.uninstall']]