services:
  nhds.jobs.foreman:
    class: NHDS\Jobs\Foreman
    calls:
      - [addDbConnectionContainer, ['@nhds.jobs.db.connection.container-job']]
      - [setJob, ['@nhds.jobs.data.job']]
      - [setSemaphore, ['@nhds.jobs.semaphore']]
      - [addSemaphoreResource, ['maintain', '@nhds.jobs.semaphore.resource-maintain']]
      - [addSemaphoreResource, ['schedule', '@nhds.jobs.semaphore.resource-schedule']]
      - [setSelector, ['@nhds.jobs.data.job.selector']]
      - [setMaintainer, ['@nhds.jobs.maintainer']]
      - [setScheduler, ['@nhds.jobs.scheduler']]
    shared: false
  nhds.jobs.semaphore.resource-maintain:
    class: NHDS\Jobs\Semaphore\Resource
    calls:
      - [setResourceName, ['maintain.lock']]
      - [setResourcePath, ['/tmp/nhds/jobs']]
      - [setIsBlocking, [false]]
      - [setMutex, ['@nhds.jobs.semaphore.mutex.flock']]
    shared: false
  nhds.jobs.semaphore.resource-schedule:
    class: NHDS\Jobs\Semaphore\Resource
    calls:
      - [setResourceName, ['schedule.lock']]
      - [setResourcePath, ['/tmp/nhds/jobs']]
      - [setIsBlocking, [false]]
      - [setMutex, ['@nhds.jobs.semaphore.mutex.flock']]
    shared: false
  nhds.jobs.semaphore.resource-job:
    class: NHDS\Jobs\Semaphore\Resource
    calls:
      - [setResourceName, ['server.lock']]
      - [setResourcePath, ['/tmp/nhds/jobs']]
      - [setIsBlocking, [false]]
      - [setMutex, ['@nhds.jobs.semaphore.mutex.flock']]
    shared: false
  nhds.jobs.data.job.selector:
    class: NHDS\Jobs\Data\Job\Selector
    calls:
      - [setPageSize, [50]]
      - [setOffset, [50]]
      - [addSemaphoreResource, ['job', '@nhds.jobs.semaphore.resource-job']]
      - [setCollection, ['@nhds.jobs.data.job.collection']]
    shared: false
  nhds.jobs.maintainer:
    class: NHDS\Jobs\Maintainer
    shared: false
  nhds.jobs.scheduler:
    class: NHDS\Jobs\Scheduler
    shared: false
    calls:
      - [setTime, ['@nhds.toolkit.time']]
  nhds.jobs.data.job:
    class: NHDS\Jobs\Data\Job
    shared: false
  nhds.jobs.data.job.collection:
    class: NHDS\Jobs\Data\Job\Collection
    calls:
      - [setIterator, ['@nhds.jobs.data.job.collection.iterator']]
      - [addDbConnectionContainer, ['@nhds.jobs.db.connection.container-job']]
      - [setModel, ['@nhds.jobs.data.job']]
    shared: false
  nhds.jobs.data.job.collection.iterator:
    class: NHDS\Jobs\Data\Job\Collection\Iterator
    shared: false