services:
  nhds.jobs.foreman:
    class: NHDS\Jobs\Foreman
    shared: false
    calls:
      - [setTypeRepository, ['@type.repository']]
      - [setSelector, ['@selector']]
      - [setLocator, ['@worker.locator']]
      - [setSemaphore, ['@semaphore']]
      - [addSemaphoreResourceFactory, ['@semaphore.resource.factory-job']]
      - [setServiceUpdateWorkFactory, ['@service.update.work.factory']]
      - [setServiceUpdatePanicFactory, ['@service.update.panic.factory']]
      - [setServiceUpdateCrashFactory, ['@service.update.crash.factory']]
      - [setServiceUpdateCompleteSuccessFactory, ['@service.update.complete.success.factory']]
      - [setLogger, ['@process.pool.logger']]
      - [setWorkerJobService, ['@worker.job.service']]
      - [setStateService, ['@state.service']]
      - [setMessageBroker, ['@message.broker.redis']]
  foreman:
    alias: nhds.jobs.foreman