services:
  nhds.jobs.foreman:
    class: NHDS\Jobs\Foreman
    shared: false
    calls:
      - [addDbConnectionContainer, ['@nhds.jobs.db.connection.container-job']]
      - [setJob, ['@nhds.jobs.data.job']]
      - [setSemaphore, ['@nhds.jobs.semaphore']]
      - [addSemaphoreResourceFactory, ['@nhds.jobs.semaphore.resource.factory-maintain']]
      - [addSemaphoreResourceFactory, ['@nhds.jobs.semaphore.resource.factory-schedule']]
      - [setSelector, ['@nhds.jobs.data.job.selector']]
      - [setMaintainer, ['@nhds.jobs.maintainer']]
      - [setScheduler, ['@nhds.jobs.scheduler']]
      - [setLocator, ['@nhds.jobs.worker.locator']]