services:
  nhds.jobs.foreman:
    class: NHDS\Jobs\Foreman
    shared: false
    calls:
      - [setJobTypeRepository, ['@nhds.jobs.data.job.type.repository']]
      - [setSelector, ['@nhds.jobs.data.job.selector']]
      - [setLocator, ['@nhds.jobs.worker.locator']]
      - [setSemaphore, ['@nhds.jobs.semaphore']]
      - [addSemaphoreResourceFactory, ['@nhds.jobs.semaphore.resource.factory-job']]
      - [setJobServiceUpdateWorkFactory, ['@nhds.jobs.data.job.service.update.work.factory']]
      - [setJobServiceUpdatePanicFactory, ['@nhds.jobs.data.job.service.update.panic.factory']]
      - [setJobServiceUpdateCrashFactory, ['@nhds.jobs.data.job.service.update.crash.factory']]
      - [setUpdateCompleteSuccessFactory, ['@nhds.jobs.data.job.service.update.complete.success.factory']]
      - [setLogger, ['@nhds.jobs.process.pool.logger']]
      - [setWorkerJobService, ['@nhds.jobs.worker.job.service']]
      - [setJobStateService, ['@nhds.jobs.data.job.state.service']]
      - [setMessageBroker, ['@nhds.jobs.message.broker.redis']]