services:
  nhds.jobs.foreman:
    class: NHDS\Jobs\Foreman
    shared: false
    calls:
      - [addDbConnectionContainer, ['@nhds.jobs.db.connection.container-job']]
      - [setJob, ['@nhds.jobs.data.job']]
      - [setSemaphore, ['@nhds.jobs.semaphore']]
      - [setSelector, ['@nhds.jobs.data.job.selector']]
      - [setLocator, ['@nhds.jobs.worker.locator']]