services:
  nhds.jobs.maintainer:
    class: NHDS\Jobs\Maintainer
    shared: false
    public: false
    calls:
      - [setSemaphore, ['@semaphore']]
      - [addSemaphoreResourceFactory, ['@semaphore.resource.factory-job']]
      - [addSemaphoreResourceFactory, ['@semaphore.resource.factory-update_pending_jobs']]
      - [addSemaphoreResourceFactory, ['@semaphore.resource.factory-reschedule_jobs']]
      - [setJobCollectionCrashDetection, ['@data.job.collection.crashdetection']]
      - [setJobCollectionScheduleLimitCheck, ['@data.job.collection.schedule.limitcheck']]
      - [setServiceUpdateCrashFactory, ['@service.update.crash.factory']]
      - [setServiceUpdateWaitFactory, ['@service.update.wait.factory']]
      - [setServiceUpdateCompleteFailedScheduleLimitCheckFactory, ['@service.update.complete.failedschedulelimitcheck.factory']]
      - [setServiceUpdatePanicFactory, ['@service.update.panic.factory']]
      - [setTypeRepository, ['@type.repository']]
      - [setJobCollectionScheduleLimit, ['@data.job.collection.schedulelimit']]
      - [setLogger, ['@process.pool.logger']]
      - [setMaintainerDelete, ['@maintainer.delete']]
  maintainer:
    alias: nhds.jobs.maintainer
    public: false