services:
  nhds.jobs.maintainer:
    class: NHDS\Jobs\Maintainer
    shared: false
    calls:
      - [setSemaphore, ['@nhds.jobs.semaphore']]
      - [addSemaphoreResourceFactory, ['@nhds.jobs.semaphore.resource.factory-job']]
      - [addSemaphoreResourceFactory, ['@nhds.jobs.semaphore.resource.factory-update_pending_jobs']]
      - [addSemaphoreResourceFactory, ['@nhds.jobs.semaphore.resource.factory-reschedule_jobs']]
      - [setJobCollectionCrashDetection, ['@nhds.jobs.data.job.collection.crashdetection']]
      - [setJobCollectionPendingLimitCheck, ['@nhds.jobs.data.job.collection.pending.limitcheck']]
      - [setJobServiceUpdateCrashFactory, ['@nhds.jobs.data.job.service.update.crash.factory']]
      - [setJobServiceUpdateWaitFactory, ['@nhds.jobs.data.job.service.update.wait.factory']]
      - [setJobServiceUpdateCancelledFailedLimitCheckFactory, ['@nhds.jobs.data.job.service.update.cancelled.failedlimitcheck.factory']]
      - [setJobTypeRepository, ['@nhds.jobs.data.job.type.repository']]
      - [setJobCollectionScheduleLimit, ['@nhds.jobs.data.job.collection.schedulelimit']]
      - [setLogger, ['@nhds.jobs.process.pool.logger']]