services:
  nhds.jobs.maintainer:
    class: NHDS\Jobs\Maintainer
    shared: false
    calls:
      - [setSemaphore, ['@nhds.jobs.semaphore']]
      - [addSemaphoreResourceFactory, ['@nhds.jobs.semaphore.resource.factory-job']]
      - [addSemaphoreResourceFactory, ['@nhds.jobs.semaphore.resource.factory-update_pending_jobs']]
      - [addSemaphoreResourceFactory, ['@nhds.jobs.semaphore.resource.factory-reschedule_jobs']]
      - [setJobCollectionCrashDetection, ['@nhds.jobs.data.job.collection.crashdetection']]
      - [setJobCollectionScheduleLimitCheck, ['@nhds.jobs.data.job.collection.schedule.limitcheck']]
      - [setJobServiceUpdateCrashFactory, ['@nhds.jobs.data.job.service.update.crash.factory']]
      - [setJobServiceUpdateWaitFactory, ['@nhds.jobs.data.job.service.update.wait.factory']]
      - [setUpdateCompleteFailedScheduleLimitCheckFactory, ['@nhds.jobs.data.job.service.update.complete.failedschedulelimitcheck.factory']]
      - [setJobServiceUpdatePanicFactory, ['@nhds.jobs.data.job.service.update.panic.factory']]
      - [setJobTypeRepository, ['@nhds.jobs.data.job.type.repository']]
      - [setJobCollectionScheduleLimit, ['@nhds.jobs.data.job.collection.schedulelimit']]
      - [setLogger, ['@process.pool.logger']]