parameters:
  process_pool_strategy.max_processes: 30
  process_pool_strategy.process_wait_throttle: 1
  process_pool_strategy.max_alarm_time: 3600
  process_pool_strategy-server.max_processes: 1
  process_pool_strategy-server.process_wait_throttle: 1
  process_pool_strategy-server.max_alarm_time: 3600