services:
  nhds.jobs.process.type.listener.command:
    class: NHDS\Jobs\Process\Type\Listener\Command
    calls:
      - [setPool, ['@nhds.jobs.process.pool']]
      - [setBrokerTypeCollection, ['@nhds.jobs.message.broker.type.collection-job']]
      - [setLogger, ['@nhds.jobs.process.pool.logger']]
      - [setBrokerTypeCode, ['job_broker']]
      - [addProcessType, ['listener.message', '@nhds.jobs.process.type.listener.command']]
      - [addProcessType, ['job', '@nhds.jobs.process.type.job']]
      - [setExpressionLanguage, ['@symfony.component.expressionlanguage.expressionlanguage']]
  nhds.jobs.process.type.job:
    class: NHDS\Jobs\Process\Type\Job
    calls:
      - [setPool, ['@nhds.jobs.process.pool']]
      - [setLogger, ['@nhds.jobs.process.pool.logger']]
      - [setBrokerTypeCollection, ['@nhds.jobs.message.broker.type.collection-job']]
      - [setBrokerTypeCode, ['job_broker']]
      - [setForeman, ['@nhds.jobs.foreman']]
#            - [setBootstrap, ['@bootstrap_example']]
  symfony.component.expressionlanguage.expressionlanguage:
    class: \Symfony\Component\ExpressionLanguage\ExpressionLanguage