services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false
imports:
   - { resource: dependencies.yml }
   - { resource: Foreman.yml }
   - { resource: tearDown.yml }
   - { resource: setup.yml }
   - { resource: Scheduler.yml }
   - { resource: Data/Job/Type/Collection.yml }
   - { resource: Data/Job/Type/Collection/Iterator.yml}
   - { resource: Data/Job/Type.yml }
   - { resource: Data/Job/Collection/Scheduler.yml }
   - { resource: Data/Job/Type/Collection/Scheduler.yml }
   - { resource: Data/Job/State/Service.yml }
   - { resource: Data/Job/Service/Create.yml }
   - { resource: Data/Job.yml }
   - { resource: Data/Job/Selector.yml }
   - { resource: Semaphore/Resource.yml }
   - { resource: Maintainer.yml }
   - { resource: Data/Job/Type/Collection.yml }
   - { resource: Process/Type/Listener/Command.yml }
   - { resource: Process/Type/Job.yml }
   - { resource: Semaphore/Mutex/Flock.yml }
   - { resource: Db/Connection/Container.yml }
   - { resource: Semaphore.yml }
   - { resource: Message/Broker/Redis.yml }
   - { resource: Process/Pool/Logger.yml }
   - { resource: Message/Broker/Type/Collection.yml }
   - { resource: Process/Pool/Server.yml }
   - { resource: Process/Pool/Strategy.yml }
   - { resource: Data/Job/Collection/Iterator.yml }
   - { resource: Semaphore/Resource/Owner/Job.yml }
   - { resource: Process/Pool.yml }
   - { resource: Data/Job/Collection/Selector.yml }
   - { resource: Data/Job/Collection/ScheduleLimit.yml }
   - { resource: Data/Job/Collection/CrashDetection.yml }
   - { resource: Data/Job/Service/Update/Crash.yml }
   - { resource: Semaphore/Resource/Factory.yml }
   - { resource: Worker/Locator.yml }
   - { resource: Data/Job/Service/Update/Crash/Factory.yml }
   - { resource: Data/Job/Service/Update/Work/Factory.yml }
   - { resource: Data/Job/Service/Update/Work.yml }
   - { resource: Data/Job/Service/Update/Cancelled/FailedLimitCheck/Factory.yml }
   - { resource: Data/Job/Service/Update/Cancelled/FailedLimitCheck.yml }
   - { resource: Data/Job/Collection/Pending/LimitCheck.yml }
   - { resource: Data/Job/Service/Create/Factory.yml }
   - { resource: Console/Command/Process/Pool/Server/Start.yml }
   - { resource: Data/Job/Type/Repository.yml }
   - { resource: Data/Job/Service/Update/Panic/Factory.yml }
   - { resource: Data/Job/Service/Update/Panic.yml }