services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false
imports:
   # External dependencies.
   - { resource: dependencies.yml }

  # Manager.
   - { resource: Foreman.yml }
   - { resource: Scheduler.yml }
   - { resource: Maintainer.yml }
   - { resource: Data/Job/Selector.yml }

   # Manger delegate.
   - { resource: Maintainer/Delete.yml }
   - { resource: Scheduler/Time.yml }
   - { resource: Scheduler/Cache.yml }

  # Data.
   - { resource: Data/Job/Type.yml }
   - { resource: Data/Job/Type/Repository.yml }
   - { resource: Data/Job/Type/Service/Create.yml }
   - { resource: Data/Job/Type/Collection.yml }
   - { resource: Data/Job/Type/Collection/Iterator.yml}
   - { resource: Data/Job/Type/Collection/Scheduler.yml }
   - { resource: Data/Job.yml }
   - { resource: Data/Job/State/Service.yml }
   - { resource: Data/Job/Collection/Scheduler.yml }
   - { resource: Data/Job/Collection/Selector.yml }
   - { resource: Data/Job/Collection/Iterator.yml }
   - { resource: Data/Job/Collection/ScheduleLimit.yml }
   - { resource: Data/Job/Collection/CrashDetection.yml }
   - { resource: Data/Job/Collection/Delete.yml }
   - { resource: Data/Job/Collection/Schedule/LimitCheck.yml }
   - { resource: Data/Job/Service/Create.yml }
   - { resource: Data/Job/Service/Create/Factory.yml }
   - { resource: Data/Job/Service/Update/Crash.yml }
   - { resource: Data/Job/Service/Update/Crash/Factory.yml }
   - { resource: Data/Job/Service/Update/Work.yml }
   - { resource: Data/Job/Service/Update/Work/Factory.yml }
   - { resource: Data/Job/Service/Update/Complete/FailedScheduleLimitCheck.yml }
   - { resource: Data/Job/Service/Update/Complete/FailedScheduleLimitCheck/Factory.yml }
   - { resource: Data/Job/Service/Update/Panic.yml }
   - { resource: Data/Job/Service/Update/Panic/Factory.yml }
   - { resource: Data/Job/Service/Update/Wait.yml }
   - { resource: Data/Job/Service/Update/Wait/Factory.yml }
   - { resource: Data/Job/Service/Update/Hold.yml }
   - { resource: Data/Job/Service/Update/Hold/Factory.yml }
   - { resource: Data/Job/Service/Update/Retry.yml }
   - { resource: Data/Job/Service/Update/Retry/Factory.yml }
   - { resource: Data/Job/Service/Update/Complete/Failed.yml }
   - { resource: Data/Job/Service/Update/Complete/Failed/Factory.yml }
   - { resource: Data/Job/Service/Update/Complete/Success.yml }
   - { resource: Data/Job/Service/Update/Complete/Success/Factory.yml }

  # Semaphore.
   - { resource: Semaphore/Resource.yml }
   - { resource: Semaphore/Resource/Owner/Job.yml }
   - { resource: Semaphore/Resource/Factory.yml }
   - { resource: Semaphore/Mutex/Flock.yml }
   - { resource: Semaphore.yml }

  # Process.
   - { resource: Process/Listener/Command.yml }
   - { resource: Process/Job.yml }
   - { resource: Process/Root.yml }
   - { resource: Process/Pool/Logger.yml }
   - { resource: Process/Pool/Server.yml }
   - { resource: Process/Pool/Strategy.yml }
   - { resource: Process/Pool/Factory.yml }
   - { resource: Process/Pool.yml }
   - { resource: Process/Collection.yml }
   - { resource: Process/Collection/Iterator.yml }
   - { resource: Process/Strategy/ProcessControl.yml }

   # Database.
   - { resource: Db/Connection/Container.yml }
   - { resource: Db/Setup.yml }
   - { resource: Db/Setup/Schema/Version_0_0_0.yml }
   - { resource: Db/Setup/Schema/Version_1_0_0.yml }
   - { resource: Db/Setup/Schema/Version_2_0_0.yml }
   - { resource: Db/Setup/Schema/Version_3_0_0.yml }
   - { resource: Db/Setup/Schema/Version_4_0_0.yml }
   - { resource: Db/Setup/Schema/Version_5_0_0.yml }
   - { resource: Db/TearDown.yml }
   - { resource: Db/TearDown/Schema/Version_0_0_0.yml }
   - { resource: Db/TearDown/Schema/Version_1_0_0.yml }
   - { resource: Db/TearDown/Schema/Version_2_0_0.yml }
   - { resource: Db/TearDown/Schema/Version_3_0_0.yml }
   - { resource: Db/TearDown/Schema/Version_4_0_0.yml }
   - { resource: Db/TearDown/Schema/Version_5_0_0.yml }

  # Message Broker.
   - { resource: Message/Broker/Redis.yml }
   - { resource: Message/Broker/Type/Collection.yml }

  # Worker.
   - { resource: Worker/Locator.yml }
   - { resource: Worker/Bootstrap.yml }
   - { resource: Worker/Job/Service.yml }

  # Console.
   - { resource: Console/Command/Process/Pool/Server/Start.yml }
   - { resource: Console/Command/Db/Setup/Install.yml }
   - { resource: Console/Command/Db/TearDown/Uninstall.yml }