services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: true
imports:
   - { resource: dependencies.yml }
   - { resource: foreman.yml }
   - { resource: server.yml }
   - { resource: process.yml }
   - { resource: tearDown.yml }
   - { resource: setup.yml }
   - { resource: Scheduler.yml }
   - { resource: Data/Job/Type/Collection.yml }
   - { resource: Data/Job/Type/Collection/Iterator.yml}
   - { resource: Data/Job/Type/Collection/Service.yml }
   - { resource: Data/Job/Type.yml }
   - { resource: Data/Job/Collection/Scheduler.yml }
   - { resource: Data/Job/Type/Collection/Scheduler.yml }