services:
  nhds.jobs.scheduler:
    class: NHDS\Jobs\Scheduler
    shared: false
    calls:
      - [setTime, ['@nhds.toolkit.time']]
      - [setCacheItemPool, ['@symfony.component.cache.adpater.redisadapter']]
      - [setSchedulerJobCollection, ['@nhds.jobs.data.job.collection.scheduler']]
      - [setSchedulerJobTypeCollection, ['@nhds.jobs.data.job.type.collection.scheduler']]
      - [setJobServiceCreate, ['@nhds.jobs.data.job.service.create']]