services:
  nhds.jobs.scheduler:
    class: NHDS\Jobs\Scheduler
    shared: false
    public: false
    calls:
      - [setTime, ['@nhds.toolkit.time']]
      - [setSchedulerJobCollection, ['@data.job.collection.scheduler']]
      - [setSchedulerJobTypeCollection, ['@data.job.type.collection.scheduler']]
      - [setServiceCreateFactory, ['@service.create.factory']]
      - [addSemaphoreResourceFactory, ['@semaphore.resource.factory-schedule']]
      - [setSchedulerCache, ['@scheduler.cache']]
  scheduler:
    alias: nhds.jobs.scheduler
    public: false