services:
  nhds.jobs.scheduler:
    class: NHDS\Jobs\Scheduler
    shared: false
    calls:
      - [setTime, ['@nhds.toolkit.time']]
      - [setSchedulerJobCollection, ['@nhds.jobs.data.job.collection.scheduler']]
      - [setSchedulerJobTypeCollection, ['@nhds.jobs.data.job.type.collection.scheduler']]
      - [setJobServiceCreateFactory, ['@nhds.jobs.data.job.service.create.factory']]
      - [addSemaphoreResourceFactory, ['@nhds.jobs.semaphore.resource.factory-schedule']]
      - [setSchedulerCache, ['@nhds.jobs.scheduler.cache']]