services:
  nhds.jobs.selector:
    class: NHDS\Jobs\Selector
    shared: true
    calls:
      - [setPageSize, [50]]
      - [setOffset, [50]]
      - [addSemaphoreResourceFactory, ['@semaphore.resource.factory-job']]
      - [setMessageBroker, ['@message.broker.redis']]
      - [setSemaphore, ['@semaphore']]
      - [setSelectorJobCollection, ['@data.job.collection.selector']]
      - [setJob, ['@data.job']]
      - [setStateService, ['@state.service']]
      - [setRandomIntMax, [10]]
  selector:
    alias: nhds.jobs.selector