services:
  nhds.jobs.process.pool.server:
    class: NHDS\Jobs\Process\Pool\Server
    calls:
      - [setLogger, ['@nhds.jobs.process.pool.logger']]
      - [setTime, ['@nhds.toolkit.time']]
      - [setPool, ['@nhds.jobs.process.pool']]
      - [addSemaphoreResource, ['server', '@nhds.jobs.semaphore.resource-server']]
      - [setSemaphore, ['@nhds.jobs.semaphore']]
  nhds.jobs.semaphore.resource-server:
    class: NHDS\Jobs\Semaphore\Resource
    calls:
      - [setResourceName, ['server.lock']]
      - [setResourcePath, ['/tmp/nhds/jobs']]
      - [setIsBlocking, [true]]
      - [setMutex, ['@nhds.jobs.semaphore.mutex.flock']]
    shared: false
  nhds.jobs.process.pool:
    class: NHDS\Jobs\Process\Pool
    calls:
      - [setLogger, ['@nhds.jobs.process.pool.logger']]
      - [setStrategy, ['@nhds.jobs.process.pool.strategy']]
  nhds.jobs.process.pool.strategy:
    class: NHDS\Jobs\Process\Pool\Strategy
    calls:
      - [setMaxProcesses, ['%process_pool_strategy.max_processes%']]
      - [setProcessWaitThrottle, ['%process_pool_strategy.process_wait_throttle%']]
      - [setMaxAlarmTime, ['%process_pool_strategy.max_alarm_time%']]
      - [setLogger, ['@nhds.jobs.process.pool.logger']]
      - [setPool, ['@nhds.jobs.process.pool']]
      - [addProcessType, ['listener.message', '@nhds.jobs.process.type.listener.command']]
      - [addProcessType, ['job', '@nhds.jobs.process.type.job']]