services:
  setup:
    class: NHDS\Jobs\Db\Setup
    calls:
      - [addVersion, ["@setup_schema_version_0_0_0"]]
      - [addVersion, ["@setup_schema_version_1_0_0"]]
      - [addVersion, ["@setup_schema_version_2_0_0"]]
      - [addVersion, ["@setup_schema_version_3_0_0"]]
      - [addVersion, ["@setup_schema_version_4_0_0"]]
      - [addVersion, ["@setup_schema_version_5_0_0"]]
  setup_schema_version_0_0_0:
    class: NHDS\Jobs\Db\Setup\Schema\Version_0_0_0
    calls:
      - [addDbConnectionContainer, ["@db_connection_container_schema"]]
  setup_schema_version_1_0_0:
    class: NHDS\Jobs\Db\Setup\Schema\Version_1_0_0
    calls:
      - [addDbConnectionContainer, ["@db_connection_container_schema"]]
  setup_schema_version_2_0_0:
    class: NHDS\Jobs\Db\Setup\Schema\Version_2_0_0
    calls:
      - [addDbConnectionContainer, ["@db_connection_container_schema"]]
  setup_schema_version_3_0_0:
    class: NHDS\Jobs\Db\Setup\Schema\Version_3_0_0
    calls:
      - [addDbConnectionContainer, ["@db_connection_container_schema"]]
  setup_schema_version_4_0_0:
    class: NHDS\Jobs\Db\Setup\Schema\Version_4_0_0
    calls:
      - [addDbConnectionContainer, ["@db_connection_container_schema"]]
  setup_schema_version_5_0_0:
    class: NHDS\Jobs\Db\Setup\Schema\Version_5_0_0
    calls:
      - [addDbConnectionContainer, ["@db_connection_container_schema"]]