services:
  tear_down:
    class: NHDS\Jobs\Db\TearDown
    calls:
      - [addVersion, ["@tear_down_schema_version_5_0_0"]]
      - [addVersion, ["@tear_down_schema_version_4_0_0"]]
      - [addVersion, ["@tear_down_schema_version_3_0_0"]]
      - [addVersion, ["@tear_down_schema_version_2_0_0"]]
      - [addVersion, ["@tear_down_schema_version_1_0_0"]]
      - [addVersion, ["@tear_down_schema_version_0_0_0"]]
  tear_down_schema_version_0_0_0:
    class: NHDS\Jobs\Db\TearDown\Schema\Version_0_0_0
    calls:
      - [addDbConnectionContainer, ["@db_connection_container_schema"]]
  tear_down_schema_version_1_0_0:
    class: NHDS\Jobs\Db\TearDown\Schema\Version_1_0_0
    calls:
      - [addDbConnectionContainer, ["@db_connection_container_schema"]]
  tear_down_schema_version_2_0_0:
    class: NHDS\Jobs\Db\TearDown\Schema\Version_2_0_0
    calls:
      - [addDbConnectionContainer, ["@db_connection_container_schema"]]
  tear_down_schema_version_3_0_0:
    class: NHDS\Jobs\Db\TearDown\Schema\Version_3_0_0
    calls:
      - [addDbConnectionContainer, ["@db_connection_container_schema"]]
  tear_down_schema_version_4_0_0:
    class: NHDS\Jobs\Db\TearDown\Schema\Version_4_0_0
    calls:
      - [addDbConnectionContainer, ["@db_connection_container_schema"]]
  tear_down_schema_version_5_0_0:
    class: NHDS\Jobs\Db\TearDown\Schema\Version_5_0_0
    calls:
      - [addDbConnectionContainer, ["@db_connection_container_schema"]]