services:
  neighborhoods.pylon.time:
    class: Neighborhoods\Toolkit\Time
  symfony.component.expressionlanguage.expressionlanguage:
    class: \Symfony\Component\ExpressionLanguage\ExpressionLanguage
  neighborhoods.kojo.symfony.component.console.application:
    public: true
    class: Symfony\Component\Console\Application
    calls:
      - [add, ['@console.command.process.pool.server.start']]
      - [add, ['@console.command.db.setup.install']]
      - [add, ['@console.command.db.tear_down.uninstall']]