services:
  nhds.jobs.process.type.listener.command:
    class: NHDS\Jobs\Process\Type\Listener\Command
    calls:
      - [setTypeCode, ['listener.command']]
      - [setPool, ['@nhds.jobs.process.pool']]
      - [setBrokerTypeCollection, ['@nhds.jobs.message.broker.type.collection-job']]
      - [setLogger, ['@nhds.jobs.process.pool.logger']]
      - [setBrokerTypeCode, ['job_broker']]
      - [addProcessType, ['@nhds.jobs.process.type.listener.command']]
      - [addProcessType, ['@nhds.jobs.process.type.job']]
      - [setExpressionLanguage, ['@symfony.component.expressionlanguage.expressionlanguage']]
