services:
  nhds.jobs.service.update.work.factory:
    class: NHDS\Jobs\Service\Update\Work\Factory
    calls:
      - [setStateService, ['@state.service']]
      - [setServiceUpdateWork, ['@service.update.work']]
  service.update.work.factory:
    alias: nhds.jobs.service.update.work.factory