services:
  nhds.jobs.db.setup.schema.version.2_0_0:
    class: NHDS\Jobs\Db\Setup\Schema\Version_2_0_0
    calls:
      - [addDbConnectionContainer, ["@db.connection.container-schema"]]
  db.setup.schema.version.2_0_0:
    alias: nhds.jobs.db.setup.schema.version.2_0_0