services:
  nhds.jobs.db.setup.schema.version_6_0_0:
    class: NHDS\Jobs\Db\Setup\Schema\Version_6_0_0
    calls:
      - [addDbConnectionContainer, ['@db.connection.container-schema']]
  db.setup.schema.version_6_0_0:
    alias: nhds.jobs.db.setup.schema.version_6_0_0