services:
  nhds.jobs.jobs.db.setup.schema.version.5_0_0:
    class: NHDS\Jobs\Db\Setup\Schema\Version_5_0_0
    calls:
      - [addDbConnectionContainer, ["@nhds.jobs.db.connection.container-schema"]]