services:
  Neighborhoods\Kojo\State\ServiceInterface:
    class: Neighborhoods\Kojo\State\Service
    shared: false
    calls:
      - [setTime, ['@Neighborhoods\Kojo\TimeInterface']]
      - [setJobTypeRepository, ['@Neighborhoods\Kojo\Job\Type\RepositoryInterface']]