services:
  neighborhoods.kojo.process.signal:
    class: Neighborhoods\Kojo\Process\Signal
    public: false
    shared: true
  process.signal:
    alias: neighborhoods.kojo.process.signal
    public: false