services:
  neighborhoods.kojo.process.signal:
    class: Neighborhoods\Kojo\Process\Signal
    public: false
    shared: true
    calls:
      - [setLogger, ['@process.pool.logger']]
      - [setProcessSignalInformationFactory, ['@process.signal.information.factory']]
  process.signal:
    alias: neighborhoods.kojo.process.signal
    public: false