services:
  nhds.jobs.worker.job.service:
    class: NHDS\Jobs\Worker\Job\Service
    shared: false
    calls:
      - [setServiceCreateFactory, ['@service.create.factory']]
      - [setServiceUpdateCompleteFailedFactory, ['@service.update.complete.failed.factory']]
      - [setServiceUpdateCompleteSuccessFactory, ['@service.update.complete.success.factory']]
      - [setServiceUpdateHoldFactory, ['@service.update.hold.factory']]
      - [setServiceUpdateRetryFactory, ['@service.update.retry.factory']]
  worker.job.service:
    alias: nhds.jobs.worker.job.service