services:
  nhds.jobs.maintainer.delete:
    class: NHDS\Jobs\Maintainer\Delete
    calls:
      - [setLogger, ['@process.pool.logger']]
      - [setJobCollectionDelete, ['@data.job.collection.delete']]
      - [addSemaphoreResourceFactory, ['@semaphore.resource.factory-maintainer_delete']]
      - [setSemaphore, ['@semaphore']]
      - [setPageSize, [50]]
      - [setOffset, [50]]
  maintainer.delete:
    alias: nhds.jobs.maintainer.delete