services:
  nhds.jobs.service.create.factory:
    class: NHDS\Jobs\Service\Create\Factory
    calls:
      - [setStateService, ['@state.service']]
      - [setServiceCreate, ['@service.create']]
      - [setJobCollectionScheduleLimit, ['@data.job.collection.schedulelimit']]
      - [setJobType, ['@data.job.type']]
      - [setJob, ['@data.job']]
  service.create.factory:
    alias: nhds.jobs.service.create.factory