services:
  nhds.jobs.db.tear_down.schema.version.5_0_0:
    class: NHDS\Jobs\Db\TearDown\Schema\Version_5_0_0
    calls:
      - [addDbConnectionContainer, ["@db.connection.container-schema"]]
  db.tear_down.schema.version.5_0_0:
    alias: nhds.jobs.db.tear_down.schema.version.5_0_0