services:
  nhds.jobs.db.teardown.schema.version.4_0_0:
    class: NHDS\Jobs\Db\TearDown\Schema\Version_4_0_0
    calls:
      - [addDbConnectionContainer, ["@nhds.jobs.db.connection.container-schema"]]