services:
  neighborhoods.kojo.db.tear_down.schema.version.1_0_0:
    class: Neighborhoods\Kojo\Db\TearDown\Schema\Version_1_0_0
    calls:
      - [addDbConnectionContainer, ["@db.connection.container-schema"]]
  db.tear_down.schema.version.1_0_0:
    alias: neighborhoods.kojo.db.tear_down.schema.version.1_0_0