services:
  neighborhoods.kojo.db.setup:
    class: Neighborhoods\Kojo\Db\Setup
    calls:
      - [addVersion, ["@db.setup.schema.version.0_0_0"]]
      - [addVersion, ["@db.setup.schema.version.1_0_0"]]
      - [addVersion, ["@db.setup.schema.version.2_0_0"]]
      - [addVersion, ["@db.setup.schema.version.3_0_0"]]
      - [addVersion, ["@db.setup.schema.version.4_0_0"]]
      - [addVersion, ["@db.setup.schema.version.5_0_0"]]
      - [addVersion, ["@db.setup.schema.version_6_0_0"]]
  db.setup:
    alias: neighborhoods.kojo.db.setup