services:
  nhds.jobs.process.listener.command:
    class: NHDS\Jobs\Process\Listener\Command
    calls:
      - [setTypeCode, ['listener.command']]
      - [setPool, ['@nhds.jobs.process.pool']]
      - [setBrokerTypeCollection, ['@nhds.jobs.message.broker.type.collection-job']]
      - [setLogger, ['@nhds.jobs.process.pool.logger']]
      - [setBrokerTypeCode, ['job_broker']]
      - [setExpressionLanguage, ['@symfony.component.expressionlanguage.expressionlanguage']]
      - [setProcessCollection, ['@nhds.jbs.process.collection']]
      - [setProcessStrategy, ['@process.strategy']]