services:
  nhds.jobs.process.listener.command:
    class: NHDS\Jobs\Process\Listener\Command
    calls:
      - [setTypeCode, ['listener.command']]
      - [setBrokerTypeCollection, ['@nhds.jobs.message.broker.type.collection-job']]
      - [setLogger, ['@process.pool.logger']]
      - [setBrokerTypeCode, ['job_broker']]
      - [setExpressionLanguage, ['@symfony.component.expressionlanguage.expressionlanguage']]
      - [setProcessCollection, ['@process.collection']]
      - [setProcessStrategy, ['@process.strategy.process_control']]
  process.listener.command:
    alias: nhds.jobs.process.listener.command