services:
  nhds.jobs.semaphore.mutex.redis:
    class: NHDS\Jobs\Semaphore\Mutex\Redis
    shared: false
    public: false
    calls:
      - [setLogger, ['@process.pool.logger']]
      - [setRedis, ['@redis']]
      - [setProcessRegistry, ['@process.registry']]
  semaphore.mutex.redis:
    alias: nhds.jobs.semaphore.mutex.redis
    public: false