services:
  nhds.jobs.scheduler.cache:
    class: NHDS\Jobs\Scheduler\Cache
    shared: true
    calls:
      - [setSchedulerTime, ['@scheduler.time']]
      - [setCacheItemPoolRepository, ['@cache_item_pool.repository']]
      - [setTime, ['@nhds.toolkit.time']]
  scheduler.cache:
    alias: nhds.jobs.scheduler.cache