services:
  nhds.jobs.scheduler.cache:
    class: NHDS\Jobs\Scheduler\Cache
    shared: true
    calls:
      - [setSchedulerTime, ['@scheduler.time']]
      - [setCacheItemPool, ['@symfony.component.cache.adpater.redisadapter']]
      - [setTime, ['@nhds.toolkit.time']]
  scheduler.cache:
    alias: nhds.jobs.scheduler.cache