services:
  nhds.jobs.scheduler.time:
    class: NHDS\Jobs\Scheduler\Time
    shared: true
    calls:
      - [setMinutesToScheduleAheadFor, [5]]
      - [setTime, ['@nhds.toolkit.time']]
  scheduler.time:
    alias: nhds.jobs.scheduler.time