services:
  neighborhoods.kojo.semaphore.mutex.redis:
    class: Neighborhoods\Kojo\Semaphore\Mutex\Redis
    shared: false
    public: false
    calls:
      - [setLogger, ['@process.pool.logger']]
      - [setRedisRepository, ['@redis.repository']]
      - [setProcessRegistry, ['@process.registry']]
  semaphore.mutex.redis:
    alias: neighborhoods.kojo.semaphore.mutex.redis
    public: false