services:
  neighborhoods.kojo.redis.repository:
    class: Neighborhoods\Kojo\Redis\Repository
    public: false
    shared: true
    calls:
      - [setProcessRegistry, ['@process.registry']]
      - [setRedisFactory, ['@redis.factory']]
  redis.repository:
    alias: neighborhoods.kojo.redis.repository
    public: false