services:
  nhds.jobs.process.collection:
    shared: true
    class: NHDS\Jobs\Process\Collection
    calls:
      - [setIterator, ['@process.collection.iterator']]
      - [addProcessPrototype, ['@process.listener.command']]
      - [addProcessPrototype, ['@process.job.required']]
      - [addProcessPrototype, ['@process.job']]
  process.collection:
    alias: nhds.jobs.process.collection
  nhds.jobs.process.collection-server:
    shared: true
    class: NHDS\Jobs\Process\Collection
    calls:
      - [setIterator, ['@process.collection.iterator']]
      - [addProcessPrototype, ['@process.root']]
  process.collection-server:
    alias: nhds.jobs.process.collection-server