services:
  nhds.jobs.process.collection:
    class: NHDS\Jobs\Process\Collection
    shared: false
    calls:
      - [setIterator, ['@nhds.jobs.process.collection.iterator']]
      - [addProcessPrototype, ['@nhds.jobs.process.listener.command']]
      - [addProcessPrototype, ['@nhds.jobs.process.job']]
  nhds.jobs.process.collection-server:
    class: NHDS\Jobs\Process\Collection
    shared: false
    calls:
      - [setIterator, ['@nhds.jobs.process.collection.iterator']]
      - [addProcessPrototype, ['@nhds.jobs.process.root']]