services:
  nhds.jobs.process.job:
    class: NHDS\Jobs\Process\Job
    calls:
      - [setLogger, ['@process.pool.logger']]
      - [setForeman, ['@foreman']]
      - [setMaintainer, ['@maintainer']]
      - [setScheduler, ['@scheduler']]
      - [setBootstrap, ['@worker.bootstrap']]
      - [setTypeCode, ['job']]
      - [setProcessStrategy, ['@process.strategy.process_control']]
  process.job:
    alias: nhds.jobs.process.job