services:
  nhds.jobs.process.job:
    class: NHDS\Jobs\Process\Job
    calls:
      - [setLogger, ['@process.pool.logger']]
      - [setForeman, ['@nhds.jobs.foreman']]
      - [setMaintainer, ['@nhds.jobs.maintainer']]
      - [setScheduler, ['@nhds.jobs.scheduler']]
      - [setBootstrap, ['@worker.bootstrap']]
      - [setTypeCode, ['job']]
      - [setProcessStrategy, ['@process.strategy']]