services:
  nhds.jobs.process.pool:
    class: NHDS\Jobs\Process\Pool
    shared: false
    calls:
      - [setLogger, ['@process.pool.logger']]
      - [setProcessSignal, ['@process.signal']]
  process.pool:
    alias: nhds.jobs.process.pool