services:
  nhds.watch.testcase.service:
    class: NHDS\Watch\TestCase\Service
    calls:
      - [addExpressionValue, ['time', '@nhds.toolkit.time']]
      - [addExpressionValue, ['numberPool', '@nhds.watch.fixture.expression.numberpool']]