services:
  nhds.watch.testcase.service:
    public: true
    class: Neighborhoods\Scaffolding\TestCase\Service
    calls:
      - [addExpressionValue, ['time', '@nhds.toolkit.time']]
      - [addExpressionValue, ['numberPool', '@nhds.watch.fixture.expression.numberpool']]